server.port: 0

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/notificationdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin

    jpa:
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          format_sql: true
          show_sql: true
      open-in-view: false
      default_batch_fetch_size: 1000

  logging.level:
    com.justpickup: DEBUG