server.port: 0

spring:
  application:
    name: discount-service

  datasource:
    url: jdbc:postgresql://localhost:5432/discountdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000

eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    com.justpickup: DEBUG

# jpa query, parameter 로그 (p6spy)
decorator.datasource.p6spy:
  enable-logging: true