:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:


[[overview]]
= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `PATCH`
| 기존 리소스의 일부를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `204 No Content`
| 기존 리소스를 성공적으로 수정함.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `404 Not Found`
| 요청한 리소스가 없음.

| `409 Conflict`
| 클라이언트의 요청이 서버의 상태와 충돌이 발생한 경우.
|===

== 카테고리 (점주 서비스)
=== 카테고리 조회
operation::get-categoryList[snippets='curl-request,http-request,http-response,request-headers,response-fields']


== 상품
=== 상품 조회
operation::item-get[snippets='curl-request,http-request,http-response,path-parameters,response-fields']
=== 상품 조회 - 존재하지 않는 상품
operation::item-get-notExistItemException[snippets='curl-request,http-request,http-response,path-parameters,response-fields']
=== 상품 리스트 조회
operation::items-get[snippets='curl-request,http-request,http-response,path-parameters,response-fields']

== 상품 (점주 서비스)
=== 상품 리스트 조회
operation::owner-itemList-get[snippets='curl-request,http-request,http-response,request-headers,request-parameters,response-fields']
=== 상품 조회
operation::owner-item-get[snippets='curl-request,http-request,http-response,path-parameters,response-fields']
=== 상품 등록
operation::owner-create-item[snippets='curl-request,http-request,http-response,request-headers,request-fields']
=== 상품 수정
operation::owner-put-item[snippets='curl-request,http-request,http-response,request-headers,request-fields']

== 상품 (사용자 서비스)
=== 상품 리스트 조회
operation::customer-itemList-get[snippets='curl-request,http-request,http-response,path-parameters,response-fields']
=== 상품 조회
operation::customer-item-get[snippets='curl-request,http-request,http-response,path-parameters,response-fields']

== 매장
=== 매장 조회
operation::store-get[snippets='curl-request,http-request,http-response,path-parameters,response-fields']
=== 매장 리스트 조회
operation::stores-get[snippets='curl-request,http-request,http-response,path-parameters,response-fields']

== 매장 (점주 서비스)
=== 사용자 고유번호로 매장 조회
operation::api-get-store-byUserId[snippets='curl-request,http-request,http-response,request-headers,response-fields']
=== 매장 등록
operation::api-post-store[snippets='curl-request,http-request,http-response,request-headers,request-fields']

== 매장 (사용자 서비스)
=== 즐겨찾는 매장 조회
operation::favoriteStore-get[snippets='curl-request,http-request,http-response,request-headers,request-parameters,response-fields']
=== 매장 검색 조회
operation::api-customer-store-search[snippets='curl-request,http-request,http-response,request-parameters,response-fields']

// itemcustomerapicontrollertest

== 즐겨찾는 매장 (사용자 서비스)
=== 즐겨찾는 매장 조회
operation::get-favoritestore-by-storeid[snippets='curl-request,http-request,http-response,request-headers,path-parameters,response-fields']

=== 즐겨찾는 매장 추가 | 제거
operation::patch-FavoriteStore[snippets='curl-request,http-request,http-response,request-headers,path-parameters']

