server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: git@github.com:Development-team-1/config-repo.git
          ignore-local-ssh-settings: true
          private-key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIGd6xXSqRoSbY8I5vFisgRKtiyC3pOh/BMiNIDhI3F+yoAoGCCqGSM49
            AwEHoUQDQgAEPs/brJDoCCEZBQUpmOPG25+BFK8MkUtUwxFNsP0naNUc1QHCBPLA
            /eeneJgj2i4UKdWqzlg41BfqeuAtIre5cQ==
            -----END EC PRIVATE KEY-----
          default-label: master
