server:
  port: 12343

spring:
  application:
    name: store-servcie
  config:
    import: optional:configserver:http://127.0.0.1:8888
  cloud:
    config:
      name: service

  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/storedb
    username: postgres
    password: admin


eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    com.justpickup: DEBUG

# jpa query, parameter 로그 (p6spy)
decorator.datasource.p6spy:
  enable-logging: true

#feign key
token:
  feign: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmZWlnbiIsImV4cCI6MTE2NDY5NzY4NzAsImlhdCI6MTY0Njk3Njg3MH0.5x4Nx7oMnpF0_kZpbZsiB1u9eEbQ4IKIhJlEsa3D22cjZjvTHKz57GCz0sgXb_olhSNIVv9xF41A29-XYiFeBQ